<?php

define('CHOSEN_DROPDOWN_FIELD_DIR', basename(dirname(__FILE__)));
define('CHOSEN_DROPDOWN_FIELD_JAVASCRIPT', CHOSEN_DROPDOWN_FIELD_DIR.'/javascript/');
define('CHOSEN_DROPDOWN_FIELD_DIR_THIRD_PARTY_DIR', CHOSEN_DROPDOWN_FIELD_JAVASCRIPT.'thirdparty/');